import { colors as sharedColors } from "./tokens";

export const colors = {
  primary: sharedColors.brandPrimary,
  primaryLight: sharedColors.brandPrimaryLight,
  primaryDark: sharedColors.brandPrimaryDark,
  secondary: sharedColors.brandSecondary,
  secondaryLight: "#d0f0fd",
  accent1: sharedColors.bio,
  accent2: sharedColors.art,
  accent3: sharedColors.arch,
  bg: sharedColors.bg,
  bgCard: sharedColors.snowWhite,
  bgCardHover: "#f7f7f7",
  text: sharedColors.text,
  textSecondary: sharedColors.textSecondary,
  textMuted: sharedColors.textMuted,
  border: sharedColors.border,
};

export const theme = {
  isDark: false,
  background: colors.bg,
  backgroundCard: colors.bgCard,
  backgroundSecondary: sharedColors.bgSecondary,
  textPrimary: colors.text,
  textSecondary: colors.textSecondary,
  textMuted: colors.textMuted,
  textAccent: colors.primary,
  primaryAction: colors.primary,
  secondaryAction: colors.secondary,
  primary: colors.primary,
  primaryLight: colors.primaryLight,
  secondary: colors.secondary,
  secondaryLight: colors.secondaryLight,
  accentPurple: sharedColors.bio,
  danger: sharedColors.danger,
  divider: sharedColors.border,
  border: colors.border,
  borderStrong: "#b5b5b5",
  panelSoft: "#f7f7f7",
  warning: sharedColors.warning,
};
