import { colors as sharedColors } from "./tokens";

export const colors = {
  primary: sharedColors.brandPrimary,
  primaryLight: "#FF8A50",
  primaryDark: "#B93A0B",
  secondary: sharedColors.brandSecondary,
  secondaryLight: "#FFD166",
  accent1: sharedColors.bio,
  accent2: sharedColors.art,
  accent3: sharedColors.arch,
  bg: sharedColors.background,
  bgCard: sharedColors.panel,
  bgCardHover: "rgba(255, 255, 255, 0.10)",
  text: sharedColors.text,
  textSecondary: sharedColors.textSecondary,
  textMuted: sharedColors.textMuted,
  border: sharedColors.border,
};

export const theme = {
  isDark: true,
  background: colors.bg,
  backgroundCard: colors.bgCard,
  backgroundSecondary: sharedColors.backgroundElevated,
  textPrimary: colors.text,
  textSecondary: colors.textSecondary,
  textMuted: colors.textMuted,
  textAccent: colors.primaryLight,
  primaryAction: colors.primary,
  secondaryAction: colors.secondary,
  primary: colors.primary,
  primaryLight: colors.primaryLight,
  secondary: colors.secondary,
  secondaryLight: colors.secondaryLight,
  accentPurple: sharedColors.bio,
  danger: sharedColors.danger,
  divider: "rgba(255,255,255,0.08)",
  border: colors.border,
  borderStrong: sharedColors.borderStrong,
  panelSoft: sharedColors.panelSoft,
  warning: sharedColors.warning,
};
